name: Auto Video Agent

on:
  schedule:
    # Publie toutes les 6 heures (UTC) → ~02h/08h/14h/20h en France l'été
    - cron: "0 */6 * * *"
  workflow_dispatch:
    inputs:
      ACCOUNT:
        description: "Compte (ex: trucs-malins)"
        required: true
        default: "trucs-malins"
      POSTS_TO_PUBLISH:
        description: "Nombre de publications à poster"
        required: true
        default: "1"
      DRY_RUN:
        description: "true = simulation, false = publication réelle"
        required: true
        default: "false"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python dependencies (same interpreter)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install Playwright + Chromium (same interpreter)
        run: |
          python -m pip install playwright==1.46.0
          python -m playwright install --with-deps chromium

    
- name: Run agent
  env:
    ACCOUNT: ${{ github.event.inputs.ACCOUNT }}
    POSTS_TO_PUBLISH: ${{ github.event.inputs.POSTS_TO_PUBLISH }}
    DRY_RUN: ${{ github.event.inputs.DRY_RUN }}
    TIKTOK_COOKIE: ${{ secrets.TIKTOK_COOKIE }}
    TIKTOK_UA: ${{ secrets.TIKTOK_UA }}
  run: |
    python main.py
