name: Agent vidéo automatique

on:
  workflow_dispatch:
    inputs:
      video_path:
        description: "Chemin vers la vidéo à publier"
        required: false
        default: "assets/test.mp4"

jobs:
  courir:
    runs-on: ubuntu-latest

    # Variables d’environnement pour l’exécution
    env:
      # Chemin vidéo saisi à l’exécution (fallback sur la valeur par défaut)
      VIDEO_PATH: ${{ github.event.inputs.video_path || 'assets/test.mp4' }}
      # Cookies TikTok en JSON (définis dans les Secrets du repo)
      TIKTOK_COOKIE: ${{ secrets.TIKTOK_COOKIE }}
      # Divers
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONUNBUFFERED: "1"
      PLAYWRIGHT_BROWSERS_PATH: "0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Installer dépendances Python + Playwright
        run: |
          python -m pip install --upgrade pip
          # Si requirements.txt existe, on l’installe (sinon on ignore sans échec)
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          pip install playwright
          python -m playwright install --with-deps chromium

      - name: Exécuter l’agent
        run: python main.py

      # Artefacts utiles pour déboguer (compatibles v4)
      - name: Déposer artefacts (logs/captures) si présents
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: agent-output
          path: |
            logs/
            traces/
            playwright-report/
            **/*.png
          if-no-files-found: ignore
