name: Agent vidéo automatique

on:
  # Déclenchement manuel depuis l'onglet "Actions"
  workflow_dispatch:
    inputs:
      ACCOUNT:
        description: "Compte (ex: 'trucs→malins')"
        required: true
        default: "trucs→malins"
      POSTS_TO_PUBLISH:
        description: "Nombre de publications à effectuer"
        required: true
        default: "1"
      DRY_RUN:
        description: "TRUE = simulation, FALSE = publication réelle"
        required: true
        default: "FALSE"

  # (Optionnel) Planifie des exécutions régulières — commente ou ajuste si besoin
  # schedule:
  #   - cron: "0 */6 * * *"   # toutes les 6h (UTC)

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system deps (ffmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Upgrade pip + install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install Playwright + Chromium (same interpreter)
        run: |
          python -m pip install playwright==1.46.0
          python -m playwright install --with-deps chromium

      - name: Run agent
        env:
          ACCOUNT: ${{ github.event.inputs.ACCOUNT }}
          POSTS_TO_PUBLISH: ${{ github.event.inputs.POSTS_TO_PUBLISH }}
          DRY_RUN: ${{ github.event.inputs.DRY_RUN }}
          TIKTOK_COOKIE: ${{ secrets.TIKTOK_COOKIE }}
          TIKTOK_UA: ${{ secrets.TIKTOK_UA }}
        run: |
          python main.py
