name: courir

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # facultatif : tous les jours à 06:00 UTC

permissions:
  contents: read

jobs:
  courir:
    runs-on: ubuntu-latest

    env:
      ACCOUNT: ${{ vars.ACCOUNT || 'trucs-malins' }}
      POSTS_TO_PUBLISH: ${{ vars.POSTS_TO_PUBLISH || '1' }}
      DRY_RUN: ${{ vars.DRY_RUN || 'False' }}
      # Secrets à définir dans Settings > Secrets and variables > Actions
      TIKTOK_COOKIE: ${{ secrets.TIKTOK_COOKIE }}
      TIKTOK_UA: ${{ secrets.TIKTOK_UA }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip + install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright + Chromium (same interpreter)
        run: |
          python -m playwright install --with-deps chromium

      # (Optionnel) Nettoyage d’anciens artefacts locaux
      - name: Prepare trace folder
        run: |
          rm -rf trace playwright-report || true
          mkdir -p trace

      - name: Run agent
        id: run_agent
        shell: bash
        run: |
          set -euo pipefail
          echo "### Lancement de main.py" >> $GITHUB_STEP_SUMMARY
          python main.py
        # Si ton script génère une trace Playwright, garde le "if: always()" ci-dessous pour upload

      # ─────────────────────────────────────────────
      #  UPLOAD DES ARTEFACTS (version v4 obligatoire)
      # ─────────────────────────────────────────────

      - name: Zip trace folder (if exists)
        if: always()
        run: |
          if [ -d "trace" ]; then
            (cd trace && zip -9 -r ../trace.zip .) || true
          fi
          if [ -d "playwright-report" ]; then
            (cd playwright-report && zip -9 -r ../playwright-report.zip .) || true
          fi

      - name: Upload Playwright trace (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trace
          path: trace.zip
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload Playwright HTML report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report.zip
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-logs
          path: |
            **/*.log
            logs/**
          if-no-files-found: ignore
          retention-days: 7
