name: Agent vidéo automatique

on:
  # Déclenchement manuel avec paramètres
  workflow_dispatch:
    inputs:
      ACCOUNT:
        description: "Compte cible (ex: trucs-malins)"
        required: true
        default: "trucs-malins"
      POSTS_TO_PUBLISH:
        description: "Nombre de publications à effectuer"
        required: true
        default: "1"
      DRY_RUN:
        description: "TRUE = simulation / FALSE = publication réelle"
        required: true
        default: "FALSE"
  # Planification optionnelle (toutes les 6h)
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: read

jobs:
  run:
    name: courir
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Variables d'environnement (inputs + secrets)
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PLAYWRIGHT_BROWSERS_PATH: "0"
      PYTHONUNBUFFERED: "1"

      ACCOUNT: ${{ github.event.inputs.ACCOUNT }}
      POSTS_TO_PUBLISH: ${{ github.event.inputs.POSTS_TO_PUBLISH }}
      DRY_RUN: ${{ github.event.inputs.DRY_RUN }}

      # ⬇️ Secrets à définir dans Settings → Secrets and variables → Actions
      TIKTOK_COOKIE: ${{ secrets.TIKTOK_COOKIE }}
      TIKTOK_UA: ${{ secrets.TIKTOK_UA }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip + install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install playwright
          fi

      - name: Install Playwright + Chromium (même interpréteur)
        run: |
          python -m playwright install --with-deps chromium

      - name: Debug rapide
        run: |
          echo "ACCOUNT=$ACCOUNT"
          echo "POSTS_TO_PUBLISH=$POSTS_TO_PUBLISH"
          echo "DRY_RUN=$DRY_RUN"
          ls -la
          ls -la assets || true

      - name: Exécuter l'agent
        run: |
          python main.py
